# cat_names = []
# while True:
#     print('Enter the name of cat ' + str(len(cat_names) + 1) +
#     ' (Or enter nothing to stop.):')
#     name = input()
#     if name == '':
#         break
#     cat_names = cat_names + [name] # List concatenation
# print('The cat names are:')
# for name in cat_names:
#     print(' ' + name)

# -----------------------------------------------------

# supplies = ['pens', 'staplers', 'flamethrowers', 'binders']
# for index, item in enumerate(supplies):
#     print(f'Index {index} in supplies is: {item} ')

# _______________________________________________________________

# import copy

# spam = ['a', 'b', 'c']
# chese = copy.copy(spam)
# chese[1] = 42
# print(spam)
# print(chese)

# ------------------------------------

